<?php

namespace App\Services;

use RuntimeException;

/**
 * Read-only search index over the official PSGC dataset generated by
 * `php artisan psgc:convert` (resources/data/psgc/psgc.json).
 *
 * Design decisions (Phase 1):
 * - Pure in-memory lookup: the decoded dataset is memoized statically per
 *   absolute file path so a single request decodes the JSON at most once.
 * - No database, no HTTP, no configuration dependency: address search must
 *   keep working even when MySQL is unavailable.
 * - Deterministic ranking: exact name match first, then prefix matches, then
 *   substring matches; inside a tier results are ordered by name length,
 *   then name, then PSGC code. The same query always yields the same list.
 * - Case- and accent-insensitive matching (explicit character map, no intl
 *   extension required) while labels always display official PSA names.
 */
class PsgcIndex
{
    /**
     * Minimum normalized query length. A one-character query such as "s"
     * matches a large share of the dataset and is not clinically useful.
     */
    public const MIN_QUERY_LENGTH = 2;

    /**
     * Character map applied after lowercasing for accent-insensitive search.
     * Keys must be lowercase: normalize() lowercases first. This keeps
     * matching deterministic across platforms (no ext-intl dependency).
     */
    private const ACCENT_MAP = [
        'á' => 'a', 'à' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' => 'a',
        'é' => 'e', 'è' => 'e', 'ê' => 'e', 'ë' => 'e',
        'í' => 'i', 'ì' => 'i', 'î' => 'i', 'ï' => 'i',
        'ó' => 'o', 'ò' => 'o', 'ô' => 'o', 'õ' => 'o', 'ö' => 'o',
        'ú' => 'u', 'ù' => 'u', 'û' => 'u', 'ü' => 'u',
        'ý' => 'y', 'ÿ' => 'y',
        'ñ' => 'n',
        'ç' => 'c',
    ];

    /** Maximum accepted limit so a single query cannot materialize the whole index. */
    public const MAX_LIMIT = 50;

    /** @var array<string, array{list: array<int, array<string, mixed>>, byCode: array<int|string, array<string, mixed>>}> */
    private static array $cache = [];

    /** @var array<int, array<string, mixed>> */
    private array $list;

    /** @var array<int|string, array<string, mixed>> */
    private array $byCode;

    public function __construct(?string $path = null)
    {
        $path = $path ?? resource_path('data/psgc/psgc.json');
        $key = realpath($path) ?: $path;

        if (!isset(self::$cache[$key])) {
            self::$cache[$key] = self::load($path);
        }

        $this->list = self::$cache[$key]['list'];
        $this->byCode = self::$cache[$key]['byCode'];
    }

    /**
     * Clears the static dataset memo. Used by tests; never needed in
     * production because the memo is per-process and the file is immutable
     * between deployments.
     */
    public static function flush(): void
    {
        self::$cache = [];
    }

    /**
     * Returns up to $limit address suggestions for a user query.
     *
     * Every row has the shape:
     * ['code' => string, 'name' => string, 'level' => string,
     *  'parent' => ?string, 'label' => string]
     *
     * An empty array is returned for short, empty or invalid UTF-8 queries.
     *
     * @return array<int, array{code: string, name: string, level: string, parent: ?string, label: string}>
     */
    public function search(string $query, int $limit = 12): array
    {
        if ($limit < 1) {
            return [];
        }

        $limit = min($limit, self::MAX_LIMIT);

        if (!mb_check_encoding($query, 'UTF-8')) {
            return [];
        }

        $q = self::normalize($query);
        if (mb_strlen($q) < self::MIN_QUERY_LENGTH) {
            return [];
        }

        $exact = [];
        $prefix = [];
        $substring = [];

        foreach ($this->list as $i => $node) {
            $norm = $node['norm'];
            if ($norm === '') {
                continue;
            }

            if ($norm === $q) {
                $exact[] = $i;
            } elseif (str_starts_with($norm, $q)) {
                $prefix[] = $i;
            } elseif (str_contains($norm, $q)) {
                $substring[] = $i;
            }
        }

        $comparator = function (int $a, int $b): int {
            $na = $this->list[$a]['norm'];
            $nb = $this->list[$b]['norm'];

            $byLength = mb_strlen($na) <=> mb_strlen($nb);
            if ($byLength !== 0) {
                return $byLength;
            }

            $byName = strcmp($na, $nb);
            if ($byName !== 0) {
                return $byName;
            }

            return strcmp($this->list[$a]['code'], $this->list[$b]['code']);
        };

        $ordered = [];
        foreach ([$exact, $prefix, $substring] as $tier) {
            usort($tier, $comparator);
            foreach ($tier as $i) {
                $ordered[] = $i;
            }
            if (count($ordered) >= $limit) {
                break;
            }
        }

        $results = [];
        foreach (array_slice($ordered, 0, $limit) as $i) {
            $results[] = $this->row($i);
        }

        return $results;
    }

    /**
     * Looks up a single node by its 10-digit PSGC code.
     *
     * @return array{code: string, name: string, level: string, parent: ?string, label: string}|null
     */
    public function findByCode(?string $code): ?array
    {
        if ($code === null || preg_match('/^\d{10}$/', $code) !== 1) {
            return null;
        }

        if (!isset($this->byCode[$code])) {
            return null;
        }

        return $this->rowFor($this->byCode[$code]);
    }

    /**
     * Returns the ancestor chain of a node from root to leaf
     * (region first, the node itself last).
     *
     * @return array<int, array{code: string, name: string, level: string, parent: ?string}>
     */
    public function hierarchy(string $code): array
    {
        if (preg_match('/^\d{10}$/', $code) !== 1 || !isset($this->byCode[$code])) {
            return [];
        }

        $chain = [];
        $cursor = $code;
        // Defensive depth guard: the generated dataset is validated acyclic at
        // conversion time, but a stuck walk must never hang a web request.
        for ($depth = 0; $cursor !== null && isset($this->byCode[$cursor]) && $depth < 10; $depth++) {
            $node = $this->byCode[$cursor];
            $chain[] = [
                'code' => $node['code'],
                'name' => $node['name'],
                'level' => $node['level'],
                'parent' => $node['parent'],
            ];
            $cursor = $node['parent'];
        }

        return array_reverse($chain);
    }

    /**
     * Builds the full human-readable label, e.g.
     * "Muzon South, City of San Jose Del Monte, Bulacan, Central Luzon".
     *
     * Segments run leaf to root (barangay first, region last), which is how
     * Philippine addresses are written.
     *
     * Region names are reduced to their inner name when the official name has
     * the form "Region III (Central Luzon)". Non-conforming names
     * (e.g. "National Capital Region (NCR)") are kept verbatim.
     * Labels always display official PSA names; accents are preserved.
     */
    public function label(?string $code): ?string
    {
        $chain = $code === null ? [] : $this->hierarchy($code);
        if ($chain === []) {
            return null;
        }

        $segments = [];
        foreach (array_reverse($chain) as $node) {
            $segments[] = $node['level'] === 'Reg'
                ? self::regionLabel($node['name'])
                : $node['name'];
        }

        return implode(', ', $segments);
    }

    /**
     * Reduces "Region III (Central Luzon)" to "Central Luzon".
     * Returns the original name when it does not follow that pattern.
     */
    public static function regionLabel(string $regionName): string
    {
        if (preg_match('/^Region\s+[IVXLCDM]+(?:-[A-Z])?\s*\((.+)\)$/u', $regionName, $m) === 1) {
            return $m[1];
        }

        return $regionName;
    }

    /**
     * Normalizes free text for matching: trims, collapses whitespace,
     * lowercases and folds accents. Returns '' for invalid UTF-8.
     */
    public static function normalize(string $text): string
    {
        if (!mb_check_encoding($text, 'UTF-8')) {
            return '';
        }

        $text = trim($text);
        if ($text === '') {
            return '';
        }

        $collapsed = preg_replace('/\s+/u', ' ', $text);
        if ($collapsed === null) {
            return '';
        }

        return strtr(mb_strtolower($collapsed, 'UTF-8'), self::ACCENT_MAP);
    }

    /**
     * @return array{list: array<int, array<string, mixed>>, byCode: array<int|string, array<string, mixed>>}
     */
    private static function load(string $path): array
    {
        if (!is_file($path)) {
            throw new RuntimeException("PSGC dataset not found at {$path}. Run php artisan psgc:convert first.");
        }

        $raw = file_get_contents($path);
        if ($raw === false) {
            throw new RuntimeException("Unable to read PSGC dataset at {$path}.");
        }

        $decoded = json_decode($raw, true);
        if (!is_array($decoded) || !isset($decoded['nodes']) || !is_array($decoded['nodes'])) {
            throw new RuntimeException("PSGC dataset at {$path} is not a valid JSON object with a nodes array.");
        }

        $list = [];
        $byCode = [];

        foreach ($decoded['nodes'] as $node) {
            if (!isset($node['code'], $node['name'], $node['level']) || !is_string($node['code'])) {
                throw new RuntimeException("PSGC dataset at {$path} contains a malformed node.");
            }

            $enriched = [
                'code' => $node['code'],
                'name' => $node['name'],
                'level' => $node['level'],
                'parent' => $node['parent'] ?? null,
                'norm' => self::normalize($node['name']),
            ];

            $list[] = $enriched;
            $byCode[$node['code']] = $enriched;
        }

        return ['list' => $list, 'byCode' => $byCode];
    }

    /**
     * Builds an output row (without the internal normalized name) and
     * attaches the full label.
     *
     * @param array{code: string, name: string, level: string, parent: ?string, norm?: string} $node
     *
     * @return array{code: string, name: string, level: string, parent: ?string, label: string}
     */
    private function row(int $index): array
    {
        return $this->rowFor($this->list[$index]);
    }

    /**
     * @param array{code: string, name: string, level: string, parent: ?string, norm?: string} $node
     *
     * @return array{code: string, name: string, level: string, parent: ?string, label: string}
     */
    private function rowFor(array $node): array
    {
        return [
            'code' => $node['code'],
            'name' => $node['name'],
            'level' => $node['level'],
            'parent' => $node['parent'],
            'label' => $this->label($node['code']) ?? (string) $node['name'],
        ];
    }
}
